### ISSUE TITLE
Complete the Monad Hierarchy

### ISSUE THREAD

**Issue by bkc39** [bkc39/ocaml-prelude#1]
The plan is to have the functor hierarchy completely integrated as the main control structure of all of the types exported in `Data` so that they all export a common, complete, coherent API rather than the sparse one in `Pervasives`. This has a few subtasks:
- [ ] Define the Monad signature and the functor to create one from an Applicative. #2 
- [ ] Implement all of the major Monad transformers. #3 
- [ ] Use the Monad transformers to implement the concrete Monads via `MonadT Identity` #4
- [ ] Implement the MonadPlus signature. #5 

This is not difficult and most of the code can be copied nearly verbatim from [ocaml-monadic](https://github.com/bkc39/ocaml-monadic/).
